# These are supported funding model platforms

github: eapo
patreon: eaposztrof
open_collective: # Replace with a single Open Collective username
ko_fi: eaposztrof
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: eapo
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://PayPal.Me/eapo', 'https://budapest.bitcoinwallet.com']
